matrix:
    include:
        - name: "Python 3.5"
          language: python
          sudo: required
          dist: xenial
          python: 
            - 3.5
          before_install:
            - sudo apt-get -qq update
            - sudo apt-get install -y ghostscript
            - sudo apt-get install -y gcc
          install:
            - pip install Cython
            - pip install -e .
            - mhcflurry-downloads fetch
            - pip install swagger-spec-validator==2.1.0
            - pip install connexion==1.4.2
            - pip install bokeh==0.13.0
            - pip install tornado==5.0.2
            - pip install jsonschema==2.6.0
            - pip install mhcnuggets==2.2
            - pip install tensorflow==1.14.0
            - pip install keras==2.2.5
          services:
            - postgresql
          script:
            - TEST_FLAG=1 python3 -m unittest discover -v
        - name: "Python 3.6"
          language: python
          sudo: required
          dist: xenial
          python: 3.6
          before_install:
            - sudo apt-get -qq update
            - sudo apt-get install -y ghostscript
            - sudo apt-get install -y gcc
          install:
            - pip install -e .
            - mhcflurry-downloads fetch
            - pip install swagger-spec-validator==2.1.0
            - pip install connexion==1.4.2
            - pip install bokeh==0.13.0
            - pip install tornado==5.0.2
            - pip install jsonschema==2.6.0
            - pip install mhcnuggets==2.2
            - pip install tensorflow==1.14.0
            - pip install keras==2.2.5
            - pip install pandas==0.25.2
          services:
            - postgresql
          script:
            - TEST_FLAG=1 python3 -m unittest discover -v
        - name: "Python 3.7"
          language: python
          sudo: required
          dist: xenial
          python: 3.7
          before_install:
            - sudo apt-get -qq update
            - sudo apt-get install -y ghostscript
            - sudo apt-get install -y gcc
          install:
            - pip install -e .
            - mhcflurry-downloads fetch
            - pip install swagger-spec-validator==2.1.0
            - pip install connexion==1.4.2
            - pip install bokeh==0.13.0
            - pip install tornado==5.0.2
            - pip install jsonschema==2.6.0
            - pip install mhcnuggets==2.2
            - pip install tensorflow==1.14.0
            - pip install keras==2.2.5
            - pip install pandas==0.25.2
          services:
            - postgresql
          script:
            - TEST_FLAG=1 python3 -m unittest discover -v
