name: py37
dependencies:
- openssl
- pip
- python=3.7.2
- readline
- sqlite
- tk
- wheel
- zlib
- requests
- pillow
- pip:
  - sphinxjp.themes.basicstrap
  - sphinxcontrib-programoutput
  - pvactools
